### ISSUE TITLE
change const variable make error

### ISSUE THREAD

**Issue by Yuiffy** [jsstuff/xspans#4]
https://github.com/jsstuff/xspans/blob/bb01115b04d6af197ac953245b849a5f88338c64/xspans.js#L295

```output = [a,b]```
output is const, throw error, 
TypeError: Assignment to constant variable.

**Comment by kobalicek** [comment]
Hello, can you elaborate? I don't see `output` being const there.

**Comment by Yuiffy** [comment]
sorry I didn't see the code on github, it is not const.
I see the error when I use it by npm.
http://registry.npm.taobao.org/xspans/download/xspans-1.0.0.tgz
in the npm package, the output is const.

**Comment by kobalicek** [comment]
Ok I see maybe it's time for an updated release

**Comment by kobalicek** [comment]
I have just released v1.0.1 - let me know whether it's all OK and I would close this issue

**Comment by ryanking1809** [comment]
Confirmed! Thanks!
